version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: "currency-exchange-db"
      POSTGRES_USER: "java"
      POSTGRES_PASSWORD: "java"
    ports:
      - "15432:5432"
    volumes:
      - ./scripts/.:/docker-entrypoint-initdb.d/.
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: