version: "3.9"

services:
  backend:
    image: currency-exchange:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - $APP_LOCAL_PORT:$APP_DOCKER_PORT
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=$POSTGRESQL_DOCKER_PORT
      - DB_NAME=$POSTGRESQL_DB
      - DB_USER=$POSTGRESQL_USER
      - DB_PASSWORD=$POSTGRESQL_PASSWORD

  db:
    image: postgres:16
    env_file: ./.env
    environment:
      POSTGRES_DB: $POSTGRESQL_DB
      POSTGRES_USER: $POSTGRESQL_USER
      POSTGRES_PASSWORD: $POSTGRESQL_PASSWORD
    ports:
      - $POSTGRESQL_LOCAL_PORT:$POSTGRESQL_DOCKER_PORT
    volumes:
#      - ./scripts/.:/docker-entrypoint-initdb.d/.
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: